cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'puma/puma'

brew 'ack'
brew 'asdf'
brew 'coreutils'
brew 'go'
brew 'grc'
brew 'imagemagick'
brew 'jp2a'
brew 'libgit2'
brew 'openssl'
brew 'mysql'
brew 'node'
brew 'readline'
brew 'postgresql'
brew 'puma/puma/puma-dev'
brew 'ruby-build'
brew 'roundup'
brew 'spaceman-diff'
brew 'spark'
brew 'terragrunt', args: ['ignore_dependencies'] 
brew 'tfenv'
brew 'unrar'
brew 'wget'

cask 'google-chrome'
cask 'slack'
cask 'atom'
